version: '3.8'

services:
  server:
    build: ./server
    container_name: minidiscord-server
    environment:
      - NODE_ENV=production
      - PORT=15000
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_ANNOUNCED_IP=${SERVER_PUBLIC_IP}
      - CORS_ORIGIN=https://voicechat.ibnsina.cc
    ports:
      - "15000:15000"
      - "15001:15001"  # For HTTPS/WSS
    volumes:
      - ./server:/app
      - /app/node_modules
      - /etc/letsencrypt/live/voicechat.ibnsina.cc/fullchain.pem:/app/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/voicechat.ibnsina.cc/privkey.pem:/app/certs/privkey.pem:ro
    restart: unless-stopped
    networks:
      - minidiscord-net
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  client:
    build: ./client
    container_name: minidiscord-client
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - /etc/letsencrypt/live/voicechat.ibnsina.cc/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/voicechat.ibnsina.cc/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - minidiscord-net

networks:
  minidiscord-net:
    driver: bridge
